### ISSUE TITLE
What is the license of this project? Please help to clarify

### ISSUE THREAD

**Issue by bobquest33** [UmSenhorQualquer/pyforms#100]

**Comment by UmSenhorQualquer** [comment]
The project repository has the MIT license, but I don't really care. You can use it as you want, just be careful in the case you use pyforms-gui, because it is based on PyQt which has some use restrictions.

**Comment by mo-han** [comment]
@UmSenhorQualquer 
> just be careful in the case you use pyforms-gui, because it is based on PyQt which has some use restrictions

Why not replace it with PySide2? PySide2 is licensed under LGPL.
