### ISSUE TITLE
Cannot switch to other fields after clicking (get focus) a ControlText field 

### ISSUE THREAD

**Issue by cajomferro** [UmSenhorQualquer/pyforms#12]

**Comment by marcelstoer** [comment]
Found this as well. The very first example I tried from https://github.com/UmSenhorQualquer/pyforms/blob/master/tutorials/1.SimpleExamples/SimpleExample1/SimpleExample1.py...and it failed. Very disappointing.

The "First name" text field is always writable but the others are not. You can right-click them and past text through the context menu but not enter text otherwise.

**Comment by UmSenhorQualquer** [comment]
Hi Marcel, I tried the example and it worked fine...all the fields are editable...
I am using Ubuntu, which operating system are you using?
And which pyforms version you have installed? do you have the last version of the Master branch?

**Comment by marcelstoer** [comment]
I tried on Windows and on OS X. pyforms was installed with `pip install pyforms` but I judging from /usr/local/lib/python2.7/site-packages/PyForms-0.1.3.dist-info I'd guess this installed 0.1.3. This, however, is not the latest as per https://github.com/UmSenhorQualquer/pyforms/releases.

Furthermore I found out that in most cases the control _will_ eventually become editable but you have to click 2-3x with the mouse. Navigating focus with the tab key fails.

**Comment by UmSenhorQualquer** [comment]
The pyforms version on pypi is outdated... I think that this issue does not happen with the current version of the master brach...
Can you try it? in the meanwhile I will update the pyforms version on pypi...

**Comment by marcelstoer** [comment]
Is the result of running `pip install pyforms` and "clone from GitHub" plus `python setup.py install` the same (apart from the version)? Or would I create a mess if I have two different pyforms versions from two different sources (pypi, manually installed)?

**Comment by UmSenhorQualquer** [comment]
By running [pip] once and after [setup.py install] you will create 2 diferent versions.
The best way to fix this is:
- first, go to the python site-packages folder and remove all the pyforms references you can find.
- after, run the command [pip install git+https://github.com/UmSenhorQualquer/pyforms.git --upgrade] to install the pyforms on the master branch.

**Comment by UmSenhorQualquer** [comment]
my advice is that you should never use the command [setup.py install] again. Instead you should use [pip install . --upgrade]. 
Pip does a better management of the python packages and if you use it you will be able for example, to uninstall packages using the command [pip uninstall <package>], with the [setup.py install] you need to remove packages manually.

**Comment by marcelstoer** [comment]
Sorry Ricardo this is turning into a Python/pip debug session. It's obviously all new to me. I didn't know you can pass `pip` a non-pypi source - very nice.

pyforms installed just fine but pysettings was missing. So, I installed that one as well but it appears to be missing `pysettings.conf`.

```
/tmp > pip install git+https://github.com/UmSenhorQualquer/pyforms.git --upgrade
Collecting git+https://github.com/UmSenhorQualquer/pyforms.git
  Cloning https://github.com/UmSenhorQualquer/pyforms.git to /private/var/folders/wv/jxj2s9317y14dsclm57bptyh0000gn/T/pip-7k8Ot9-build
Installing collected packages: PyForms
  Running setup.py install for PyForms ... done
Successfully installed PyForms-0.1.7.3 
/tmp > python SimpleExample.py 
Traceback (most recent call last):
  File "SimpleExample.py", line 4, in <module>
    import pyforms
  File "/usr/local/lib/python2.7/site-packages/pyforms/__init__.py", line 4, in <module>
    from pysettings import conf;
ImportError: No module named pysettings
/tmp > pip install pysettings
Collecting pysettings
  Downloading PySettings-0.1.90.tar.gz
Building wheels for collected packages: pysettings
  Running setup.py bdist_wheel for pysettings ... done
  Stored in directory: /Users/marcelstoer/Library/Caches/pip/wheels/a8/9d/1c/cdf76403a5cdd6a067e8a7ad0633dbcdd22e003088fdd4cb04
Successfully built pysettings
Installing collected packages: pysettings
Successfully installed pysettings-0.1.90
/tmp > python SimpleExample.py 
Traceback (most recent call last):
  File "SimpleExample.py", line 4, in <module>
    import pyforms
  File "/usr/local/lib/python2.7/site-packages/pyforms/__init__.py", line 4, in <module>
    from pysettings import conf;
ImportError: cannot import name conf
```

**Comment by UmSenhorQualquer** [comment]
That is fine... actually I have to thank you, because you are helping me testing pyforms and with this discussion I was able to find out several issues I have to update in the documentation...

to fix the issue you reported you can run the next commands [pip install git+https://github.com/UmSenhorQualquer/pysettings.git --upgrade] and [pip install git+git clone https://UmSenhorQualquer@bitbucket.org/fchampalimaud/logging-bootstrap.git --upgrade]

**Comment by marcelstoer** [comment]
That indeed fixes all the issues i.e. this issue can be closed.

Your latest command is broken, though. It should be `pip install git+https://UmSenhorQualquer@bitbucket.org/fchampalimaud/logging-bootstrap.git --upgrade`

**Comment by UmSenhorQualquer** [comment]
That's great...thank you
