### ISSUE TITLE
from pysettings import conf

### ISSUE THREAD

**Issue by ashishaware28** [UmSenhorQualquer/pyforms#38]
While run first program of pyforms i was getting pysettings error. After that i had installed pysettings module but still this error is coming conf is **ImportError: cannot import name conf**
PLease provide better solution

**Comment by JBauto** [comment]
Hi,
Did you install pyforms and pysettings from pip? They aren't updated to the latest version and you should install using the main repos.
- pip install git+https://github.com/UmSenhorQualquer/pyforms.git --upgrade
- pip install git+https://github.com/UmSenhorQualquer/pysettings.git --upgrade

(Duplicate of #37)

**Comment by ashishaware28** [comment]
thank you sir

**Comment by williamhatcher** [comment]
Please note this in the documentation.
