### ISSUE TITLE
Running from terminal / web

### ISSUE THREAD

**Issue by gsal** [UmSenhorQualquer/pyforms#40]
Say, I am following the examples.  

Tried to run the PersonWindow graphically and it runs just fine.
Tried to run from the terminal and it insists running with a GUI; then, again, it does print out a few messages:
```
$ python PersonWin.py --help
Matplot lib not installed or not working properly
GL widgets or Opencv not installed
QScintilla2 not installed
```
those were not listed as necessary requirements, are they?

Lastly, PyForms claims to offer the ability to run on the "Web", what exactly does that mean? and how to do it? 

Thanks

gsal

**Comment by atianadya** [comment]
I'm having the same problem, can't run application in terminal mode despite having a `settings.py` file inside the directory. It seems like pyforms `conf` uses the settings file that is located inside the pyforms directory, where it searches for `PYFORMS_MODE` environment variable value and if not found it picks `GUI` as the default.

For the time being I'm editing that file, but I'm not sure if I'm missing something if the settings file inside my application's directory should work.

**Comment by UmSenhorQualquer** [comment]
I have to admit that the documentation was not complete about this issue.
Hopefully now on version v4 everything is much more clear than before.

You can check how to configure the execution in the several environments here: https://pyforms.readthedocs.io/en/v4/getting-started/first-app.html
