### ISSUE TITLE
Hwo to run WEB application?

### ISSUE THREAD

**Issue by magicznykrag** [UmSenhorQualquer/pyforms#41]
When I try to run example application in WEB environment it saids: "ImportError: No module named pyforms_web.web"

Where can I find pyforms_web module?

**Comment by merlink01** [comment]
Same Problem here!

**Comment by UmSenhorQualquer** [comment]
It took me some years to stabilize the web version..

Hopefully you will now find the answer in the new documentation:
https://pyforms-web.readthedocs.io
https://pyforms.readthedocs.io/en/v4/getting-started/first-app.html
