### ISSUE TITLE
cannot import name 'ControlImage'

### ISSUE THREAD

**Issue by D-K-E** [UmSenhorQualquer/pyforms#42]
Hi, I having the following error when i am trying to import ControlImage. The traceback doesn't really make sense because i do have opencv 2.4.v5 and python bindings for QScintilla2. Any ideas ?
```
python pyform_aigyptiaka.py 
No OpenGL library available
GL widgets or Opencv not installed
VisVis not installed
QScintilla2 not installed
Traceback (most recent call last):
  File "pyform_aigyptiaka.py", line 8, in <module>
    from   pyforms.Controls import ControlImage
ImportError: cannot import name 'ControlImage'

```

**Comment by teidal** [comment]
Same problem here

**Comment by UmSenhorQualquer** [comment]
If opencv is not installed the ControlImage and the ControlPlayer will not work. On version 4 if you install pyforms using pip you should have this issues anymore
