### ISSUE TITLE
ImportError: No module named loggingbootstrap

### ISSUE THREAD

**Issue by aokray** [UmSenhorQualquer/pyforms#48]
I'm currently having an issue where I can't get my basic imports to work, with the error described in the title. Whenever I search "loggingbootstrap" with any terms in tandem, I can't even find its existence except in this import statement. Currently I'm running MacOS Sierra v10.12.4 (16E195), with Anaconda as my primary environment, Python version 2.7.13. I have used the "pip install git+[REPO NAME HERE] --upgrade" command for pyforms and pysettings and I still can't get it to work.

**Comment by cajomferro** [comment]
Hello aokray,

You probably are missing this library: https://bitbucket.org/fchampalimaud/logging-bootstrap. Have you installed it already?

Cheers,
Carlos

**Comment by aokray** [comment]
Looks like that worked, thanks!

aokray

**Comment by mihow** [comment]
Should this be added to setup.py or the docs?

**Comment by WayneKeenan** [comment]
This should be added to the docs or as a dependency in setup.py

**Comment by TaylorDennisLee** [comment]
Just had this same problem. It should be added as a dependency.
