### ISSUE TITLE
Syntax error in terminal/BaseWidget

### ISSUE THREAD

**Issue by raleeper** [UmSenhorQualquer/pyforms#5]
There is a syntax error in pyforms/pyforms/terminal/BaseWidget.py on line 16. Looks like a cut-and-paste error. 
Line 16 should be: 
```python
self._parser = argparse.ArgumentParser()
```
not: 
```python
self._parser = argpaPYFORMS_MODE = 'TERMINAL'rse.ArgumentParser()
```

**Comment by UmSenhorQualquer** [comment]
Thank you for reporting the bug.
In the meanwhile a new version 0.1.1 was released with several bugs corrected including this one.
I also released some documentation here: pyforms.readthedocs.org.

Best,
