### ISSUE TITLE
Error in documentation

### ISSUE THREAD

**Issue by freddieRv** [UmSenhorQualquer/pyforms#55]
In your [readthedocs page](http://pyforms.readthedocs.io/en/v2.0/getting-started/the-basic/) you have the following example code:

`if __name__ == "__main__":   pyforms.start_app( SimpleExample1 )`

But it raises the following exception:

`AttributeError: 'module' object has no attribute 'start_app'`

So looking around in StackOverflow I found that the correct method name is

`startApp()`

I installed pyforms using pip, and I got version 0.1.7.3. I can see that the readthedocspage is for the version 2.0. I couldn't find version specific documentation, which I think is a must if you have changes as big as this snake-case to  cammel-case change.

**Comment by DanielIbaseta** [comment]
Same issue here. This solves the problem, please fix the docs.

**Comment by UmSenhorQualquer** [comment]
A few months ago the version on pypi was really outdated. 
Now I released the version v4 and updated pypi.
