### ISSUE TITLE
What am I doing wrong

### ISSUE THREAD

**Issue by jromano1** [UmSenhorQualquer/pyforms#56]
Using Sublime text 3, copied exactly your code and get
NameError: name 'BaseWidget' is not defined

**Comment by UmSenhorQualquer** [comment]
You probably were using the wrong pyforms version in the wrong application. Check the new documentation and let me know if the issue still happen.

Thank you

**Comment by jromano1** [comment]
Thank you for the response - I'm far from adept at even the most basic python coding - but if step 1 is 
pip install pyforms
How can I have the wrong version?

**Comment by UmSenhorQualquer** [comment]
Just to make sure you have the latest version do `pip3 install pyforms --upgrade` in the terminal.
SublimeText by default uses python2.7 to execute code, therefore try to execute the application directly on the terminal: `python3 myapp.py`

Make sure you execute the application with python3
