### ISSUE TITLE
install from pip broken/check requirements

### ISSUE THREAD

**Issue by sanzoghenzo** [UmSenhorQualquer/pyforms#57]
Hi, first of all thanks for your work!
I would like to use pyforms in my small apps, but I encounter some problems:
* if i `pip install pyforms` it installs PyForms-0.1.7.3, but if I try to run your first example it complains about pysettings missing.
* after manually installing PySettings-0.1.90 from pip, it gives me this error:
```
    from pysettings import conf
ImportError: cannot import name 'conf'
```
Looks like the pip version of pysettings is outdated, and pyforms setup.py doesn't check the requirements.

**Comment by sanzoghenzo** [comment]
In general, it seems that there's no requirements listed in setup.py

**Comment by dagrooms52** [comment]
I have this problem as well - if nobody has answered since September 30, it looks like this is a dead (or dying) project. Back to Kivy...

**Comment by JBauto** [comment]
You need to install pysettings from the repository instead of pip.
- git clone https://github.com/UmSenhorQualquer/pysettings
- cd pysettings
- pip install . --upgrade
