### ISSUE TITLE
Install Requirements with Package - PySettings

### ISSUE THREAD

**Issue by dagrooms52** [UmSenhorQualquer/pyforms#58]
I get the following error when trying to run the `pyforms` tutorial code:

```
Traceback (most recent call last):
  File "src/view/example.py", line 1, in <module>
    import pyforms
  File "/usr/local/lib/python3.6/site-packages/pyforms/__init__.py", line 4, in <module>
    from pysettings import conf;
ImportError: cannot import name 'conf'
```

Please install dependencies with your installer.

**Comment by JBauto** [comment]
You need to install pysettings from the repository instead of pip.
- git clone https://github.com/UmSenhorQualquer/pysettings
- cd pysettings
- pip install . --upgrade
