### ISSUE TITLE
loggingbootstrap

### ISSUE THREAD

**Issue by smatejcek** [UmSenhorQualquer/pyforms#59]
I've imported pyforms and pysettings from the hyperlinks as mentioned in another comment.  When I try to import pyforms, i get the error message:

In [1]: import pyforms
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-b1327b749b5b> in <module>()
----> 1 import pyforms

C:\Users\etqw5lb\AppData\Local\Continuum\anaconda3\lib\site-packages\pyforms\__init__.py in <module>()
      2 # -*- coding: utf-8 -*-
      3 import logging
----> 4 import loggingbootstrap
      5 from pysettings import conf
      6

ModuleNotFoundError: No module named 'loggingbootstrap'

Is there a series of support modules that need to me imported for pyforms?  Something else I'm doing wrong?

**Comment by dehugger** [comment]
Having the same issue, python 3.6.4

```
Traceback (most recent call last):
  File "main_new.py", line 1, in <module>
    from ui import TesterMainWindow
  File "C:\Users\Ben\Projects\axosoft-selenium\ui.py", line 1, in <module>
    import pyforms
  File "C:\Users\Ben\Projects\axosoft-selenium\venv\lib\site-packages\pyforms\__init__.py", line 4, in <module>
    import loggingbootstrap
ModuleNotFoundError: No module named 'loggingbootstrap'
```

**Comment by McAlyster** [comment]
You can install it with pip install git+https://bitbucket.org/fchampalimaud/logging-bootstrap.git

**Comment by UmSenhorQualquer** [comment]
The logging-bootstrap library was removed from pyforms. Everything can be installed using pip
