### ISSUE TITLE
AttributeError: 'xxx' object has no attribute 'mainmenu'

### ISSUE THREAD

**Issue by McAlyster** [UmSenhorQualquer/pyforms#61]
Hey, 

the update of BaseWidget.py caused a bug : 

> AttributeError: 'xxx' object has no attribute 'mainmenu'

I don't know if it's a consequence of the  addition of the AnyQt imports but I had to come back to previous BaseWidget.py (after a certain amount of time to figure out what was wrong 🍡 )
> from AnyQt.QtWidgets import QFrame
> from AnyQt.QtWidgets import QVBoxLayout
>...

The bug appears on OSX (10.13) and Linux (Mint). 
Following the SimpleExample.py should be sufficient to reproduce the error.

**Comment by UmSenhorQualquer** [comment]
Didn't find the error. Hopefully it was fixed in the meanwhile. 
Please let me know if you still have it.

Thank you.
