### ISSUE TITLE
Installing for pyqt4?

### ISSUE THREAD

**Issue by RanTalbott** [UmSenhorQualquer/pyforms#69]
I'm cross-developing for an old system that has issues with recent versions of Ubuntu, so I have it running 12.04. Which only has QT4 available. When I try to install pyforms with pip, it downloads pyforms 3.0.0, and complains that it can't find pyqt5.

How can I download a version that works with pyqt4?

Thanks,

Ran

**Comment by UmSenhorQualquer** [comment]
On version 3 the code was not fully converted to work with both QT versions.
On version 4 I replaced any Qt imports by the AnyQt library, which should solve your problem.

Please be aware that v4 has pyqt5 in the requirements, once you install Pyforms you should replace pyqt5 by the pyqt4 library.
