### ISSUE TITLE
SimpleExample finishes with exit code -1073741819 (0xC0000005) through pycharm and crashes python through terminal

### ISSUE THREAD

**Issue by Djones4822** [UmSenhorQualquer/pyforms#71]
I've copied and pasted the simple example into a python script just to test. Installed with `pip install pyforms` 

Launching with Anaconda3 Python3.6 on windows 10 x64 through Pycharm doesn't open any window and the program finishes with the exit code listed above.

Launching the same but through the terminal causes python to crash with no error. 

Tried uninstalling and reinstalling with --no-cache-dir to get a fresh download but no avail. 

this seems to suggest a memory access error:
https://social.microsoft.com/Forums/en-US/431265d6-823e-4671-ae31-6e2b7e40170f/exit-code-0xc0000005?forum=windowshpcmpi

Not sure if something wrong on my side.

**Comment by UmSenhorQualquer** [comment]
At the time the pyforms library at pypi was probably outdated, I have updated it in the meanwhile and add all the required requirements to the setup.py.

Also some months ago (not sure when) I was having the same problem and was related with the pyqt5 installation. If the pyqt5 from pypi does not work try to use a version from Anaconda.
