### ISSUE TITLE
ControlTextArea issue

### ISSUE THREAD

**Issue by Pytaya** [UmSenhorQualquer/pyforms#72]
how do I get it to display the output of the ControlTextArea in real time?

**Comment by UmSenhorQualquer** [comment]
You question is a bit vague, but if you want to for example read a buffer and display it on "RealTime" you can use QTimer from pyqt to schedule a thread function to execute from times to times, and add the read value to the Control.

def update(self):  
      text_area_control += self.buffer.read()
