### ISSUE TITLE
Can't import Controls in a new installation

### ISSUE THREAD

**Issue by SyedMuhammadAli** [UmSenhorQualquer/pyforms#74]
Just installed pyforms in Win10 with Py3.5.4. The installation was successful.

Now I get the following error when trying out the first example in the documentation:

```
Python 3.5.4 (v3.5.4:3f56838, Aug  8 2017, 02:17:05) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyforms
>>> from   pyforms          import BaseWidget
>>> from   pyforms.Controls import ControlText
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named 'pyforms.Controls'
>>> from   pyforms.Controls import ControlButton
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named 'pyforms.Controls'
>>>
>>>
>>> pyforms
<module 'pyforms' from 'C:\\Users\\meh\\AppData\\Local\\Programs\\Python\\Python35\\lib\\site-packages\\pyforms\\__init__.py'>
>>> pyforms.__version__
'3.0.0'
```

Any ideas how to fix this?

Code taken from: https://pyforms.readthedocs.io/en/v3.0/getting-started/the-basic/

**Comment by gjkf** [comment]
I had your same exact problem so I looked into the examples here and [this](https://github.com/UmSenhorQualquer/pyforms/blob/master/tutorials/1.SimpleExamples/SimpleExample1/__init__.py#L13-L17) seems to suggest that `pyforms.controls` is what should be imported, lowercase `c`.

**Comment by UmSenhorQualquer** [comment]
Davide, thank you for your help.

from the version 2.0 to 3.0 I updated the name of the modules to lower case.

Davide Cossu <notifications@github.com> escreveu no dia quarta, 8/08/2018
à(s) 09:44:

**Comment by jdt1** [comment]
I just ran into the same issue, maybe it's a good idea to update the example code so it also uses lower case.

**Comment by jtbr** [comment]
With the latest code it looks like basewidget must also be lowercase.
But even then the simplest example from the documentation fails:

> Traceback (most recent call last):
  File "test.py", line 8, in <module>
    class SimpleExample1(basewidget):
TypeError: module() takes at most 2 arguments (3 given)

Is there a stable branch (but updated enough to use pyqt5) that is usable and matches the documentation?

**Comment by UmSenhorQualquer** [comment]
With version v4 the **BaseWidget** is imported using the code: `from pyforms.basewidget import BaseWidget`. On v3 it was like: `from pyforms import BaseWidget`

On version v4 I tried to uniform the code syntax. Names of the modules in lower case, classes with capitalised names.
Therefore you should continuing using the code `class SimpleExample1(BaseWidget):` only the BaseWidget import changed.

Check the **Important updates** section of the README.md file in the pyforms repository, it explains what has changed.

Here you have also an example of an application working
https://github.com/UmSenhorQualquer/pyforms-gui/blob/v4/tutorials/1.SimpleExamples/ComputerVisionAlgorithmExample/Example.py

**Comment by kippy100** [comment]
I got an error > No module named 'pyforms'  
but I have installed trough pip3 install pyforms it said installed but when I try to run an app it says the above error...please some help

**Comment by psalrod** [comment]
I have a similar problem running the People example in (PeopleWindow.py): No module named 'AddMenuFuntionality'. It seems that is another lower/upper case issue or a mistake on the module name.
I couldn't find a solution for that so far.
