### ISSUE TITLE
[Installation/usage] issue with "incompatible Qt library" ?

### ISSUE THREAD

**Issue by neodark** [UmSenhorQualquer/pyforms#80]
Hi,

The package doesn't seem to work after installation. Can someone help please ?

This is what I did:

`$ virtualenv env --python=python3`
`$ source env/bin/activate`
`$ pip install pyforms`

Launching the example from the documentation I get the following:

```
GL widgets or Opencv is not installed
No module named 'cv2'
Traceback (most recent call last):
  File "pyforms/env/lib/python3.6/site-packages/pyforms/controls.py", line 47, in <module>
    from pyforms.gui.controls.ControlOpenGL                             import ControlOpenGL
  File "pyforms/env/lib/python3.6/site-packages/pyforms/gui/controls/ControlOpenGL.py", line 30, in <module>
    from pyforms.gui.controls.control_player.VideoGLWidget import VideoGLWidget
  File "pyforms/env/lib/python3.6/site-packages/pyforms/gui/controls/control_player/VideoGLWidget.py", line 8, in <module>
    from pyforms.gui.controls.control_player.AbstractGLWidget import AbstractGLWidget
  File "pyforms/env/lib/python3.6/site-packages/pyforms/gui/controls/control_player/AbstractGLWidget.py", line 7, in <module>
    import logging, cv2
ModuleNotFoundError: No module named 'cv2'
Cannot mix incompatible Qt library (version 0x50905) with this library (version 0x50b01)
Aborted (core dumped)
```

So I did a:
`$ pip install opencv-python`

and after executing the example.py I still get:

```
Cannot mix incompatible Qt library (version 0x50905) with this library (version 0x50b01)
Aborted (core dumped)
```
Thanks in advance for your help.

**Comment by UmSenhorQualquer** [comment]
Which operating system are you using?
The error is related with PyQt5. OpenCV is optional and is not causing this error.

How you have installed pyqt5? 
From a fresh environment try to install pyforms using: pip install pyforms

**Comment by neodark** [comment]
I have tried on Linux on both: Debian 9 and Ubuntu 18.04 with the same issue appearing.

The installed libraries are the following
`
$ pip freeze
`
```
AnyQt==0.0.8
cycler==0.10.0
kiwisolver==1.0.1
matplotlib==3.0.0
numpy==1.15.2
pkg-resources==0.0.0
PyForms==3.0.0
PyOpenGL==3.1.0
pyparsing==2.2.1
PyQt5==5.11.2
PyQt5-sip==4.19.12
python-dateutil==2.7.3
QScintilla==2.10.7
six==1.11.0
visvis==1.11.1
```

**Comment by UmSenhorQualquer** [comment]
It seems I gave you the wrong information. Opencv was mandatory. I released a new version 4.0.2 on pypi that fixes this issue. The dump shouldn't happen because of the missing opencv anymore.

Regarding the Qt dump, I am using Ubuntu 17.10 and I am not having it, when ever an error happens it shows me the traceback log and not a dump error. The main difference I find between our environments is that you are using virtualenv and I am using Anaconda.
Do you have any other environment where you have a different Qt version? including the base environment?

My Anaconda environment goes in attachment. 

[environment.txt](https://github.com/UmSenhorQualquer/pyforms/files/2424975/environment.txt)

**Comment by neodark** [comment]
Ok I created a conda environment using your file.

`$ conda env create --file ~/Downloads/environment.txt -n pyforms`
`$ conda activate pyforms`

Then I installed pyforms via pip (as there's no conda package available for it):
`$ pip install pyforms`

Then I cloned your repository again and tried your example:
`$ git clone git@github.com:UmSenhorQualquer/pyforms.git`
`$ cd pyforms`
`$ git submodule init`
`$ git submodule update`

`$ python pyforms-gui/tutorials/1.SimpleExamples/SimpleExample1/SimpleExample1.py`
```
Cannot mix incompatible Qt library (version 0x50905) with this library (version 0x50b01)
Aborted (core dumped)
```

The error I get is similar to the issue I have when I install via pip.

**Comment by neodark** [comment]
Thanks for your help.
I will close this issue as I found that the issue I had was actually located with a bad `LD_LIBRARY_PATH` after cleaning it I was able to run the test.py file and see the interface.
