### ISSUE TITLE
Set Tab Order

### ISSUE THREAD

**Issue by adammartin** [UmSenhorQualquer/pyforms#83]
I'm curious if there is a mechanism to control tab order.  It seems to default to alphabetic which results in some behavior I don't want.   I was hoping the order was controlled by the formset definition.  Is there a way to change this?

I suspect that a small change to pyforms_gui/basewidget.py line 107:

`for key, item in sorted(formsetdict.items()):`

I think the issue is that sorting.  If I'm reading it correctly it will sort it rather then leaving the structure as defined in the formset.

Thanks!

**Comment by UmSenhorQualquer** [comment]
I add some information here about ordering the tabs:
https://pyforms-gui.readthedocs.io/en/v4/getting-started/the-basic.html

You may need to refresh the page.
