### ISSUE TITLE
Link to pyforms documentation returns "this page does not exist yet" error, yet alt-text is clearly visible on Google.

### ISSUE THREAD

**Issue by malloyethan11** [UmSenhorQualquer/pyforms#84]
[This link](https://pyforms.readthedocs.io/en/latest/getting-started/the-basic/) to the pyforms documentation returns a page with the error message "this page does not exist yet." 

Also, [the page that is supposed to contain the latest version of pyforms](https://pyforms.readthedocs.io/en/latest/) is "an autogenerated index file." 

I've attached screenshots of all this to this message.

![bad pyforms link 2](https://user-images.githubusercontent.com/40256124/48996075-a2f0cf80-f118-11e8-89f3-271069023dcd.JPG)
![bad pyforms link 1](https://user-images.githubusercontent.com/40256124/48995865-b5b6d480-f117-11e8-8597-feb825e6d872.JPG)
![pyforms error whole page screencap](https://user-images.githubusercontent.com/40256124/48995870-bea7a600-f117-11e8-89b8-928b604fee31.JPG)

**Comment by UmSenhorQualquer** [comment]
Thank you for reporting this issue. The latest versions of the documentation is now working
